#!/bin/sh
pwd=`pwd`
cat <<EOF
new-window 'bash -c "echo booting the Gordon repl; cd $pwd; lein repl :connect 5557"'
split-window -v 'bash -c "cd $pwd; make riemann-server"'
split-window -v 'bash -c "cd $pwd; make mongoproxy"'
split-window -h "bash -c 'cd $pwd; sh ./script/start-reactor'"
resize-pane -D 10
select-pane -U
select-pane -U
EOF
